// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseUrl, getSupabaseKey } from '@/config/supabase';

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = getSupabaseKey();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a simple storage adapter for SSR/SSG environments
const storage = typeof window !== 'undefined' 
  ? localStorage 
  : {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    };

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      storage: storage as any,
      persistSession: typeof window !== 'undefined',
      autoRefreshToken: typeof window !== 'undefined',
    }
  }
);